name: food
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Raleway
    fonts:
      - assets: assets/fonts/Raleway-Black.ttf 
        weight: 900
      - assets: assets/fonts/Raleway-Bold.ttf 
        weight: 700
      - assets: assets/fonts/Raleway-Regular.ttf 
  - family: RobotoCondensed
    fonts:
      - assets: assets/fonts/RobotoCondensed-Bold.ttf 
        weight: 700
      - assets: assets/fonts/RobotoCondensed-Light.ttf 
        weight: 300
      - assets: assets/fonts/RobotoCondensed-Regular.ttf 
      - assets: assets/fonts/RobotoCondensed-Italic.ttf 
        style: italic
    
